name: Build
on:
  push:
  pull_request:

jobs:
  cross-build-in-docker:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.4
    env:
      # Disable the build version control system to avoid issues with Containers on GitHub Actions
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4
      - name: Make shell scripts executable
        run: find . -name "*.sh" -type f -exec chmod +x {} \;
      - name: Install cross-compilation dependencies
        run: |
          set -x
          # Enable multi-arch support for cross-compilation
          dpkg --add-architecture arm64
          apt-get update -yq
          apt-get install -yq \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libwayland-dev \
            libwayland-egl1-mesa \
            libvulkan-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb1-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxfixes-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libxkbcommon0 \
            libxkbcommon-x11-0 \
            libwayland-client0 \
            libwayland-cursor0 \
            libwayland-egl1 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcursor1 \
            libxfixes3 \
            libegl1-mesa \
            musl-dev \
            musl-tools \
            gcc-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            pkg-config \
            libxkbcommon-dev:arm64 \
            libxkbcommon-x11-dev:arm64 \
            libwayland-dev:arm64 \
            libwayland-egl1-mesa:arm64 \
            libvulkan-dev:arm64 \
            libx11-dev:arm64 \
            libx11-xcb-dev:arm64 \
            libxcb1-dev:arm64 \
            libxrandr-dev:arm64 \
            libxinerama-dev:arm64 \
            libxcursor-dev:arm64 \
            libxi-dev:arm64 \
            libxfixes-dev:arm64 \
            libegl1-mesa-dev:arm64 \
            libgl1-mesa-dev:arm64 \
            libxkbcommon0:arm64 \
            libxkbcommon-x11-0:arm64 \
            libwayland-client0:arm64 \
            libwayland-cursor0:arm64 \
            libwayland-egl1:arm64 \
            libx11-6:arm64 \
            libx11-xcb1:arm64 \
            libxcb1:arm64 \
            libxcursor1:arm64 \
            libxfixes3:arm64 \
            libegl1-mesa:arm64
      - name: Build
        run: |
          set -x
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          go env
          go mod vendor
          make all
      - name: Test
        run: |
          ./dist/linuxgnu-amd64/demo --database-url=sqlite://./test.sqlite3
          ./dist/linuxmusl-amd64/demo --database-url=sqlite://./test.sqlite3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
          compression-level: 0
          retention-days: 1
