name: Build
on:
  push:
  pull_request:

jobs:
  cross-build-in-docker:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.4
    env:
      # Disable the build version control system to avoid issues with Containers on GitHub Actions
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4
      - name: Make shell scripts executable
        run: find . -name "*.sh" -type f -exec chmod +x {} \;
      - name: Install cross-compilation dependencies
        run: |
          set -x
          # Enable multi-arch support for cross-compilation
          dpkg --add-architecture arm64
          apt-get update -yq
          apt-get install -yq \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libwayland-dev \
            libwayland-egl1-mesa \
            libvulkan-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb1-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxfixes-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libxkbcommon0 \
            libxkbcommon-x11-0 \
            libwayland-client0 \
            libwayland-cursor0 \
            libwayland-egl1 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcursor1 \
            libxfixes3 \
            libegl1-mesa \
            musl-dev \
            musl-tools \
            gcc-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            xvfb \
            imagemagick \
            fluxbox \
            tesseract-ocr \
            tesseract-ocr-eng \
            caca-utils \
            pkg-config \
            libxkbcommon-dev:arm64 \
            libxkbcommon-x11-dev:arm64 \
            libwayland-dev:arm64 \
            libwayland-egl1-mesa:arm64 \
            libvulkan-dev:arm64 \
            libx11-dev:arm64 \
            libx11-xcb-dev:arm64 \
            libxcb1-dev:arm64 \
            libxrandr-dev:arm64 \
            libxinerama-dev:arm64 \
            libxcursor-dev:arm64 \
            libxi-dev:arm64 \
            libxfixes-dev:arm64 \
            libegl1-mesa-dev:arm64 \
            libgl1-mesa-dev:arm64 \
            libxkbcommon0:arm64 \
            libxkbcommon-x11-0:arm64 \
            libwayland-client0:arm64 \
            libwayland-cursor0:arm64 \
            libwayland-egl1:arm64 \
            libx11-6:arm64 \
            libx11-xcb1:arm64 \
            libxcb1:arm64 \
            libxcursor1:arm64 \
            libxfixes3:arm64 \
            libegl1-mesa:arm64
      - name: Build
        run: |
          set -x
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          go env
          go mod vendor
          make all
      - name: Test GUI Application
        run: |
          set -x
          
          # Start Xvfb virtual framebuffer
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 &
          XVFB_PID=$!
          
          # Wait for X server to start
          sleep 2
          
          # Start lightweight window manager
          fluxbox &
          FLUXBOX_PID=$!
          
          # Wait for window manager
          sleep 2
          
          # Test the GUI application with timeout and screenshot
          echo "Testing linuxgnu-amd64 GUI application..."
          timeout 30s ./dist/linuxgnu-amd64/demo &
          APP_PID=$!
          
          # Wait a bit for the app to render
          sleep 5
          
          # Take screenshot
          import -window root screenshot-amd64.png || echo "Screenshot failed"
          
          # Analyze screenshot if it was captured
          if [ -f "screenshot-amd64.png" ]; then
            echo ""
            echo "=== OCR TEXT EXTRACTION ==="
            if tesseract screenshot-amd64.png screenshot-ocr.txt 2>/dev/null; then
              echo "Detected text:"
              cat screenshot-ocr.txt
              echo ""
              echo "Text summary: $(cat screenshot-ocr.txt | tr -d '\n' | tr -s ' ')"
            else
              echo "OCR failed"
            fi
            
            echo ""
            echo "=== ASCII ART CONVERSION ==="
            img2txt -W 80 -H 40 screenshot-amd64.png || echo "ASCII art conversion failed"
            
            echo ""
            echo "=== IMAGE INFO ==="
            identify screenshot-amd64.png || echo "Image info failed"
          else
            echo "No screenshot to analyze"
          fi
          
          # Kill the application
          kill $APP_PID 2>/dev/null || true
          wait $APP_PID 2>/dev/null || true
          
          # Clean up
          kill $FLUXBOX_PID 2>/dev/null || true
          kill $XVFB_PID 2>/dev/null || true
          
          echo "GUI test completed"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist
          compression-level: 0
          retention-days: 1
      - name: Upload Screenshot and Analysis
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gui-analysis
          path: |
            *.png
            *.txt
          retention-days: 1
