name: Build
on:
  push:
  pull_request:

jobs:
  cross-build-in-docker:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.4
    env:
      # Disable the build version control system to avoid issues with Containers on GitHub Actions
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4
      - name: Make shell scripts executable
        run: find . -name "*.sh" -type f -exec chmod +x {} \;
      - name: Install cross-compilation dependencies
        run: |
          set -x
          # Enable multi-arch support for cross-compilation
          dpkg --add-architecture arm64
          apt-get update -yq
          apt-get install -yq \
            libxkbcommon-dev \
            libwayland-dev \
            pkg-config \
            libxkbcommon-dev:arm64 \
            libwayland-dev:arm64
      - name: Build
        run: |
          set -x
          go env
          go mod vendor
          make all
      - name: Test
        run: |
          ./dist/linuxgnu-amd64/demo --database-url=sqlite://./test.sqlite3
          ./dist/linuxmusl-amd64/demo --database-url=sqlite://./test.sqlite3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
          compression-level: 0
          retention-days: 1
